version: '3'
services:
  skywalking-oap:
    image: apache/skywalking-oap-server:latest
    container_name: skywalking-oap
    environment:
      - SW_STORAGE=h2
      - SW_STORAGE_H2_MIXED=true
      - SW_STORAGE_H2_DRIVER_CLASS_NAME=org.h2.Driver
      - SW_STORAGE_H2_URL=jdbc:h2:/skywalking/data;MODE=MYSQL;DB_CLOSE_DELAY=-1
      - SW_STORAGE_H2_USERNAME=admin
      - SW_STORAGE_H2_PASSWORD=admin
    ports:
      - "11800:11800" # OTLP Receiver
      - "12800:12800" # HTTP Exporter
    volumes:
      - ./oap-config:/skywalking/config
      - ./oap-data:/skywalking/data

  skywalking-ui:
    image: apache/skywalking-ui:latest
    container_name: skywalking-ui
    ports:
      - "8080:8080"
    environment:
      - SW_OAP_ADDRESS=skywalking-oap:12800

  # spring-app:
  #   build:
  #     context: ./your-spring-app
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - skywalking-oap
